---
version: "3.7"
services:
  db:
   image: mariadb:11.4.1-rc-jammy
   restart: always
   container_name: user_db
   ports:
    - 3306:3306
   env_file:
    - .db.env
   command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
   networks:
    - proxy

  app:
   depends_on:
     - db
   build:
    context: .
    dockerfile: Dockerfile
   container_name: user_service
   restart: unless-stopped
   env_file:
     - .env
   expose:
     - 6308
   networks:
     - proxy

networks:
  proxy:
   external: true
